[package]
name = "pkhex_rs"
version = "0.0.1"
edition = "2021"

[lib]
name = "pkhex_rs"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
bytemuck = "1.13.1"
paste = "1.0.14"
pkhex_rs_macros = { path = "pkhex_rs-macros" }
